CREATE TABLE IF NOT EXISTS link
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(8) NOT NULL,
    redirect VARCHAR(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL
);
